name: gallery-benchmarks


on: [push, pull_request]


jobs:
  gallery-benchmarks:
    name: Make gallery of examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: upgrade pip and install requirements
        run: |
          pip install --upgrade pip
          pip install -r py_scripts/requirements.txt

      - name: run script
        run: |
          python py_scripts/make_gallery.py ${{ secrets.ACCESS_TOKEN }}
          